# Site settings
title: RC Blog
SEOTitle: 陈甸甸的博客 | RockentsChen Blog
header-img: img/RockentsChen.png
email: rocketschenmet@gmail.com
description: "Write the life!"
keyword: "RocketsChen, RockentsChen Blog, 陈甸甸的博客, chendiandian, 陈甸甸, iOS, Apple, iPhone"
url: "http://RocketsChen.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/RocketsChen/RocketsChen.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Believe that the road in their own feet!"
sidebar-avatar: /img/rocketsChen-gentle.jpg     # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     RocketsChen_
# zhihu_username:     RocketsChen
github_username:    RocketsChen
# facebook_username:  RocketsChen
jianshu_username:   RocketsChen
#twitter_username:   RocketsChen




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: RocketsChen

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: e1eb3389fa9b60cf1d67                            #生成的clientID
  clientSecret: 42535fa6cbf86ac16b2f0b7e5c47db3640f60875    #生成的clientSecret
  repo: RocketsChen.github.io    #仓库名称
  owner: RocketsChen    #github用户名
  admin: RocketsChen
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-130780696-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "RocketsChen",
        href: "https://github.com/RocketsChen"
    },{
        title: "简书·RocketsChen",
        href: "https://www.jianshu.com/u/4762736f28a8"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
